### ISSUE TITLE
Blog Website  "manage roles" section

### ISSUE THREAD

**Issue by gulferkocc** [babanazar06/BlogWebsiteCore#1]
Hello, I saw the video you uploaded on YouTube (Blog Website using ASP.NET CORE C#). I'm a computer engineering student, and I'd like to adapt and enhance this website for my project. I'm also curious about the data connection code for the "manage roles" section on your website. Could you please share that with me? @babanazarkamyljanov

**Comment by babanazarkamyljanov** [comment]
Hi,
It is located in Controllers/AdministrationController.cs, and views for that are located in Views/Administration/ folder.
You can hide that navigation link depending on user role as per below code:
` @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
  {
       <li class="nav-item mx-0 mx-lg-1">
             <a class="nav-link py-3 px-0 px-lg-3 rounded" asp-area="" asp-controller="Administration" asp-action="ListRoles">
                     Manage Roles
             </a>
       </li>
}`

**Comment by gulferkocc** [comment]
First of all, thank you for your response. But what I want to ask is which database application you used (SQL, PHP, etc.) and if you can provide the codes you used in them and the input data you entered? For example,create table manager  id , name varchar...

**Comment by gulferkocc** [comment]
Thank you for your response first. But what I want to ask is which database application you used (SQL, PHP, etc.) and can you provide the codes you used in them and the input data you entered? For example, create table manager  id , name varchar...

**Comment by babanazarkamyljanov** [comment]
I got you.

In my case I didn’t create tables by myself. It is automatically created
using Entity Framework Core (aka ORM you can learn about this first)
And to connect SQL Server code is in Program.cs file. Where you give local
connection string to your database.

And then using EF you can run these commands:
Add-Migration InitialCreate
Update-Database

Then you can check database, and you will sea all tables
